### ISSUE TITLE
Sass file ?

### ISSUE THREAD

**Issue by suryatresna** [akivaron/miminium#1]
Hi,
Apa template ini menggunakan SCSS sebagai engine CSS nya.?  kalau iya, di share juga file SCSS-nya jadi bisa di kembangkan lebih baik lagi.

**Comment by akivaron** [comment]
hi juga,maaf sayangnya proses development dilakukan secara langsung,mungkin kedepanya akan saya sediakan. jika anda ikut berpartisipasi dalam menyediakan dalam format sass/scss/less/sejenisnya saya sangat berterima kasih.

**Comment by krebbi** [comment]
so what language is that?

**Comment by akivaron** [comment]
@krebbi indonesian language.
