### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by edsonlima95** [akivaron/miminium#14]
When I download it, the links from left-menu does not work !

**Comment by phochs** [comment]
Same here, makes it pretty unusable

**Comment by EdgarEldy** [comment]
How can i fix the links from left-menu ? It doesn't work.

**Comment by nelbren** [comment]
1) Edit the file `asset/js/main.js`, and comment the line 5 with the content of `e.preventDefault();`, and replace with this: `//e.preventDefault();` (following the instrucctions of @phochs)
 2) In Windows (`Control+F5`) or in Mac (`Command-Shift-R`) to force the reload of javascript edited.

**Comment by EdgarEldy** [comment]
Thanks a lot Nelbren. It works now.

**Comment by mayank-mehrotra** [comment]
Thanks a lot @nelbren . It works now.

**Comment by mayank-mehrotra** [comment]
It's Again stopped working. I have removed e.preventDefault(); from main.js. Please, help :(

**Comment by edsonlima95** [comment]
Try return false. Instead

Sent from my iPhone

On 6 Apr 2017, at 13:00, mayank-mehrotra <notifications@github.com<mailto:notifications@github.com>> wrote:


It's Again stopped working. I have removed e.preventDefault(); from main.js. Please, help :(

**Comment by mathanCst** [comment]
Thanks a lot @nelbren . It works now.

**Comment by mayank-mehrotra** [comment]
How can i fix the links from mobile-menu ? It doesn't work and on click of link pages not opening. Please, help it's urgent.

**Comment by mayank-mehrotra** [comment]
For quick fix I have used javascript window.location it saved me for now but author should fix this issue or let us know how I can fix this. Thanks guys
