### ISSUE TITLE
too long delay for scroll appear when click on #left-menu .tree-toggle

### ISSUE THREAD

**Issue by jul6art** [akivaron/miminium#19]
Hi!

First, i need to congrat you for the amazing job. This theme is really amazing.

Second, i would like to know how to reduce the delay to the scroll appear when click on a #left-menu .tree-toggle?

Thanks

**Comment by akivaron** [comment]
Sorry, it seems like I don't appreciate you, I haven't worked on this project in a long time. I have fixed the issue now.

https://github.com/akivaron/miminium/pull/24
