### ISSUE TITLE
hover effect

### ISSUE THREAD

**Issue by chaudhary-99** [akivaron/miminium#29]
I can add a beautifull hover effect to the side bar buttons which will match the website design.
please @akivaron assign this issue to me.
<img width="149" alt="Screenshot 2022-10-23 at 2 27 22 AM" src="https://user-images.githubusercontent.com/113928981/197362275-8c40283e-6cec-488c-be9a-63bb62467ba0.png">

**Comment by akivaron** [comment]
Sure.. 🤟
