### ISSUE TITLE
Date Picker Broken

### ISSUE THREAD

**Issue by aslaugsollilja** [akivaron/miminium#5]
The last column in the calendar exceeds the calendar itself. 

![datepicker](https://cloud.githubusercontent.com/assets/4632426/12368386/dcefd070-bb9f-11e5-8b22-1b95a7819dcc.jpg)

**Comment by nrkkalyan** [comment]
Update the class: bootstrap-material-datetimepicker.css
The line:
.dtp table.dtp-picker-days tr > td > a, .dtp .dtp-picker-time > a { color: #BBB1B1; text-decoration: none; padding: _**0.3rem 0.4rem 0.4rem 0.2rem;**_ border-radius: 50%!important; }
